=== Ashleshk/Programming-Codes/JAVA-Advanced/ModularAdvanceJava3July/XMLDemos/superHeroDtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT superheroes (superhero+)>
<!ELEMENT superhero (name, specialPower)>
<!ELEMENT name (#PCDATA)><!ELEMENT specialPower (#PCDATA)>
<!ATTLIST superhero sid ID #REQUIRED>
<!ATTLIST superhero speciality  (CryptonionSkinCell|BatMobile) "BatMobile">

=== Ashleshk/Programming-Codes/JAVA-Advanced/ModularAdvanceJava3July/XMLDemos/Superhero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE superheroes SYSTEM "superHeroDtd.dtd">
<superheroes>

	<superhero sid="s1" speciality = "BatMobile">
		<name>Batman</name>
		<specialPower>ability to fight</specialPower>
	</superhero>
<superhero sid="s2" speciality = "CryptonionSkinCell  ">
		<name>Superman</name>
		<specialPower>ability to fly</specialPower>
	</superhero>
	  
<superhero sid="s3">
<name>SpiderMan</name>
<specialPower>Web</specialPower>
</superhero>

</superheroes>
