=== Ashleshk/Programming-Codes/JAVA-Advanced/ModularAdvanceJava3July/XMLDemos/SuperheroSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/SuperheroSchema"
xmlns:tns="http://www.example.org/SuperheroSchema" 
elementFormDefault="qualified">

<complexType name="superherosType">
<sequence>
<element name = "superhero" type="tns:superherotype" maxOccurs="3" minOccurs="1">
</element>
</sequence>
</complexType>

<complexType name="superherotype">
<sequence>
<element name= "name" type="string"></element>
<element name= "specialPower" type="string"></element>
</sequence>
<attribute name = "sid" type="ID" use = "required"></attribute>
</complexType>

<element name="globalsuperheroes" type="tns:superherosType"></element>
</schema>

=== Ashleshk/Programming-Codes/JAVA-Advanced/ModularAdvanceJava3July/XMLDemos/superSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalsuperheroes xmlns:tns="http://www.example.org/SuperheroSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SuperheroSchema SuperheroSchema.xsd ">
  <tns:superhero sid="idvalue0">
    <tns:name>tns:name</tns:name>
    <tns:specialPower>tns:specialPower</tns:specialPower>
  </tns:superhero>
  <tns:superhero sid="idvalue10">
    <tns:name>tns:name</tns:name>
    <tns:specialPower>tns:specialPower</tns:specialPower>
  </tns:superhero>
  <tns:superhero sid="idvalue2">
    <tns:name>tns:name</tns:name>
    <tns:specialPower>tns:specialPower</tns:specialPower>
  </tns:superhero>
  
  
</tns:globalsuperheroes>
